config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  post "/graphql", to: "graphql#execute"

  devise_for :users, skip: %i[passwords registrations], controllers: {
    sessions: "admin/sessions"
  }

  authenticate :user do
    root "admin#index"
    namespace :admin do
      resources :products, only: :index do
        collection do
          get "fetch_by_type", as: "fetch_products_by_type", to: "products#fetch_by_type"
          get "featured_meals", to: "products#featured_meals"
        end
        member do
          post   "set_as_featured",   as: "set_meal_as_featured",   to: "products#featured_meal"
          delete "set_as_unfeatured", as: "set_meal_as_unfeatured", to: "products#unfeatured_meal"
        end
      end
      put "value_meals/:id/update_status", as: "update_value_meal_status", to: "value_meals#update_status"
      resources :alacartes
      resources :branches, except: :show
      resources :coupons, except: :show
      resources :delivery_numbers, only: %i[edit update]
      resources :meal_options, except: :show do
        collection do
          get "fetch_sorted_meals", to: "meal_options#fetch_sorted_meals"
        end
      end
      resources :news
      resources :orders, only: :index
      resources :promos, except: :show
      resources :static_pages, only: :index
      resources :upsells, except: :show
      resources :users, except: :show
      resources :value_meals
      resources :coupon_utilizations, only: :index
      resources :variances, except: :show
      resources :notifications, except: :show
      resources :categories, except: :show
      resources :home_contents, except: :show
      resources :user_manuals, except: :show
    end
    if %i[development? staging?].any? { |e| Rails.env.send(e) }
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    end
  end
end

app/models/user_manual.rb
# == Schema Information
#
# Table name: user_manuals
#
#  created_at   :datetime         not null
#  description  :string
#  id           :integer          not null, primary key
#  image_source :string
#  sequence_id  :integer
#  updated_at   :datetime         not null
#

# Model for User Manual
class UserManual < ApplicationRecord
  mount_uploader :image_source, ImageUploader
  acts_as_list column: :sequence_id
end

app/controllers/admin/user_manuals_controller.rb
# Controller for User Manual
class Admin::UserManualsController < AdminController
  set_tab :cms
  set_tab :user_manual, :cms

  before_action :set_user_manual, only: %i[edit update destroy]

  def index
    @user_manuals = UserManual.all.page(params[:page]).per(10)
  end

  def new
    @user_manual = UserManual.new
  end

  def create
    @user_manual = UserManual.new(user_manual_params)
    if @user_manual.save
      @user_manual.insert_at(params[:sequence].to_i)
      redirect_to admin_user_manuals_path, notice: "Success!"
    else
      error_message = @user_manual.errors.full_messages.to_sentence
      redirect_to admin_user_manuals_path, alert: "Error!, #{error_message}"
    end
  end

  def edit
  end

  def update
    if @user_manual.update(user_manual_params)
      @user_manual.insert_at(params[:sequence].to_i) if params[:sequence]
      redirect_to admin_user_manuals_path, notice: "Success!"
    else
      error_message = @user_manual.errors.full_messages.to_sentence
      redirect_to admin_user_manuals_path, alert: "Error!, #{error_message}"
    end
  end

  def destroy
    @user_manual.destroy
    redirect_to admin_user_manuals_path, notice: "Success!"
  end

  private

  def user_manual_params
    params.require(:user_manual).permit(:image_source, :description)
  end

  def set_user_manual
    @user_manual = UserManual.find(params[:id])
    error_message = "Error!, record not found"
    path = admin_user_manuals_path
    redirect_to path, alert: error_message unless @user_manual
  end
end

app/helpers/admin/user_manuals_helper.rb
module Admin::UserManualsHelper
end

app/views/admin/user_manuals/_form.html.erb
<%= form_with model: [:admin, @user_manual], local: true do |f| %>
  <%= render "shared/form_errors", object: @user_manual %>
  <div class="tile">
    <div class="tile is-parent is-vertical is-6">
      <div class="field">
        <div class="control">
          <%= f.text_field :description, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Description" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.number_field :sequence, class: "input has-no-top-side-border
          is-shadowless is-radiusless is-paddingless", placeholder: "Order", required: true %>
        </div>
      </div>
      <br>
      <div class="tile is-child is-8">
        <div class="field">
          <figure class="image is-4by3">
            <%= image_tag "#{@user_manual.image_source&.url}", data: { container: "image" } %>
          </figure>
          <br>
          <div class="control">
            <label class="label button has-yellow-bg" for="photo" id="uploader-label">
              <%= photo_upload_label_for(photo_is_present: @user_manual.image_source.present?) %>
            </label>
            <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 1020x565</p>
            <%= f.file_field :image_source, id: "photo", data: { uploader: "" }, class: "is-invisible"%>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.submit "SAVE", class: "save-btn white-text has-195px-width button red-background" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/user_manuals/_user_manual_lists.html.erb
<% @user_manuals.each do |manual| %>
  <tr>
    <td><%= manual.sequence_id %></td>
    <td><%= manual.description %></td>
    <td>
      <div class="tile is-vertical">
        <%= link_to edit_admin_user_manual_path(manual), class: "edit-btn is-size-7" do %>
          <span class="icon is-small">
            <%= fa_icon "edit", class: "has-light-green-text" %>
          </span>
          EDIT
        <% end %>
        <%= link_to admin_user_manual_path(manual), class: "delete-btn is-size-7", method: :delete do %>
          <span class="icon is-small">
            <%= fa_icon "trash", class: "red-text" %>
          </span>
          DELETE
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/user_manuals/edit.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "store.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Edit User Instruction</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/user_manuals/index.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "store.png" %>
          </figure>
        </div>
        <div class="level-item has-margin-left-15">
          <h1 class="title is-3 is-black-text has-font-akzidenz-bold">User Instructions</h1>
        </div>
        <div class="level-item">
          <%= render "shared/admin/cms_menu" %>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to new_admin_user_manual_path, class: "button save-btn red-background", id: "csm-btn" do %>
            <span class="icon is-small">
              <%= fa_icon "plus", class: "white-text" %>
            </span>
            <span class="white-text font-is-akzidenz-ce-bold">CREATE USER INSTRUCTION</span>
          <% end%>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__items-table">
    <table class="table is-bordered is-fullwidth is-marginless">
      <thead>
        <tr>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Sequence</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Description</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Operations</th>
        </tr>
      </thead>
      <tbody id="paginationList">
        <%= render "user_manual_lists" %>
      </tbody>
    </table>
    <div class="tile with-25px-top-bottom-padding">
      <div class="tile is-parent is-5">
        <div class="tile is-child" id="paginator">
          <%= paginate @user_manuals, remote: true  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/user_manuals/index.js.erb
$("#paginationList").html("<%= escape_javascript(render("user_manual_lists")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@user_manuals, remote: true)) %>");

app/views/admin/user_manuals/new.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "store.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Create User Instruction</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>