config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  post "/graphql", to: "graphql#execute"

  devise_for :users, skip: %i[passwords registrations], controllers: {
    sessions: "admin/sessions"
  }

  authenticate :user do
    root "admin#index"
    namespace :admin do
      resources :products, only: :index do
        collection do
          get "fetch_by_type", as: "fetch_products_by_type", to: "products#fetch_by_type"
          get "featured_meals", to: "products#featured_meals"
        end
        member do
          post   "set_as_featured",   as: "set_meal_as_featured",   to: "products#featured_meal"
          delete "set_as_unfeatured", as: "set_meal_as_unfeatured", to: "products#unfeatured_meal"
        end
      end
      put "value_meals/:id/update_status", as: "update_value_meal_status", to: "value_meals#update_status"
      resources :alacartes
      resources :branches, except: :show
      resources :coupons, except: :show
      resources :delivery_numbers, only: %i[edit update]
      resources :meal_options, except: :show do
        collection do
          get "fetch_sorted_meals", to: "meal_options#fetch_sorted_meals"
        end
      end
      resources :news
      resources :orders, only: :index
      resources :promos, except: :show
      resources :static_pages, only: :index
      resources :upsells, except: :show
      resources :users, except: :show
      resources :value_meals
      resources :coupon_utilizations, only: :index
      resources :variances, except: :show
      resources :notifications, except: :show
      resources :categories, except: :show
      resources :home_contents, except: :show
      resources :user_manuals, except: :show
    end
    if %i[development? staging?].any? { |e| Rails.env.send(e) }
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    end
  end
end

app/models/promo.rb
# == Schema Information
#
# Table name: promos
#
#  category          :string
#  content           :text
#  created_at        :datetime         not null
#  id                :integer          not null, primary key
#  image_source      :string
#  is_active         :boolean          default(FALSE), not null
#  is_published      :boolean          default(FALSE), not null
#  link              :string
#  name              :string
#  tags              :string
#  updated_at        :datetime         not null
#  validity_end_at   :datetime
#  validity_start_at :datetime
#

# Promo Model
class Promo < ApplicationRecord
  mount_uploader :image_source, ImageUploader
  CATEGORIES = { regular: "Regular", breakfast: "Breakfast" }.freeze
  enum category: CATEGORIES

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true

  def self.active_scope(active:)
    active.nil? ? all : where(is_active: active)
  end

  def self.published_scope(published:)
    published.nil? ? all : where(is_published: published)
  end
end

app/controllers/admin/promos_controller.rb
# Controller for managing Promo Model
class Admin::PromosController < AdminController
  set_tab :cms
  set_tab :promo, :cms
  before_action :set_promo, only: %i[edit update destroy]

  def index
    @promos = Promo.all.page(params[:page]).per(10)
  end

  def new
    @promo = Promo.new
  end

  def create
    @promo = Promo.new(promo_params)
    if @promo.save
      redirect_to admin_promos_path, notice: "Success"
    else
      render :new
    end
  end

  def edit
  end

  def update
    mod_params = promo_params
    mod_params[:is_active] = mod_params.fetch("is_active", false)
    mod_params[:is_published] = mod_params.fetch("is_published", false)
    if @promo.update(mod_params)
      redirect_to admin_promos_path, notice: "Success"
    else
      render :edit
    end
  end

  def destroy
    @promo.destroy
    redirect_to admin_promos_path, notice: "Success"
  end

  private

  def set_promo
    @promo = Promo.find(params[:id])
  end

  def promo_params
    permitted_params = %i[
      name category is_active link tags is_published
      validity_start_at validity_end_at content image_source
    ]
    params.require(:promo)
          .permit(permitted_params)
  end
end

app/helpers/admin/promos_helper.rb
module Admin::PromosHelper
  def promo_categories
    ::Promo::CATEGORIES
  end
end

app/views/admin/promos/_form.html.erb
<%= form_with model: [:admin, @promo], local: true do |f| %>
  <%= render "shared/form_errors", object: @promo %>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="field">
        <div class="control">
          <%= f.text_field :name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Promo" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Category</label>
        </div>
        <div class="control">
          <div class="select">
            <%= f.select :category, options_for_select(promo_categories.collect{ |k, v| [v, k] }) %>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :link, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Order Now Link" %>
        </div>
      </div>
      <br>
      <div class="field">
        <div class="control">
          <%= f.text_field :tags, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Tags", data: { input: "tag" } %>
        </div>
      </div>
      <br>
      <div class="field">
        <input id="isActive" type="checkbox" name="promo[is_active]" class="switch is-rtl is-rounded is-success" <%= "checked" if @promo.is_active %> data-checkbox="switch">
        <label for="isActive">Active</label>
      </div>
      <br>
      <div class="field">
        <input id="isPublish" type="checkbox" name="promo[is_published]" class="switch is-rtl is-rounded is-success" <%= "checked" if @promo.is_published %> data-checkbox="switch">
        <label for="isPublish">Publish</label>
      </div>
      <br>
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <div class="control">
              <label class="label">From</label>
              <%= f.text_field :validity_start_at, data: { toggle: "datepicker" }, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Date" %>
            </div>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div class="control">
              <label class="label">To</label>
              <%= f.text_field :validity_end_at, data: { toggle: "datepicker" }, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Date" %>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.submit "SAVE", class: "save-btn white-text has-195px-width button red-background" %>
        </div>
      </div>
    </div>
      <div class="tile is-parent has-margin-left-30">
        <div class="field">
          <figure class="image is-4by3">
            <%= image_tag "#{@promo.image_source&.url}", data: { container: "image" } %>
          </figure>
          <br>
          <div class="control">
            <label class="label button has-yellow-bg" for="photo" id="uploader-label">
              <%= photo_upload_label_for(photo_is_present: @promo.image_source.present?) %>
            </label>
            <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 2000x2000</p>
            <%= f.file_field :image_source, id: "photo", data: { uploader: "" }, class: "is-invisible"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/promos/_nav.html.erb
<nav class="navbar nav-set-height is-light-gray-bg">
  <div class="container is-fluid">
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <%= tabs_tag builder: MenuTabBuilder, open_tabs: { class: "navbar-start" } do |tab| %>
        <%= tab.home "Home Page", "", class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.notification "Notifications", admin_notifications_path, class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.thank_you "Thank You Page", admin_meal_options_path(meal_type: "Extra"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.promo "Promos", admin_promos_path, class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.navigation "Navigation", "", class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.category "Category", "", class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/admin/promos/_promo_lists.html.erb
<% @promos.each do |promo| %>
  <tr>
    <td><%= promo.name %></td>
    <td>
      <div class="tile is-vertical">
        <%= link_to edit_admin_promo_path(promo), class: "edit-btn is-size-7" do %>
          <span class="icon is-small">
            <%= fa_icon "edit", class: "has-light-green-text" %>
          </span>
          EDIT
        <% end %>
        <%= link_to admin_promo_path(promo), class: "delete-btn is-size-7", method: :delete do %>
          <span class="icon is-small">
            <%= fa_icon "trash", class: "red-text" %>
          </span>
          DELETE
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/promos/edit.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "coupon.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Edit Promo</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/promos/index.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "coupon.png" %>
          </figure>
        </div>
        <div class="level-item has-margin-left-15">
          <h1 class="title is-3 is-black-text has-font-akzidenz-bold">Promos</h1>
        </div>
        <div class="level-item">
          <%= render "shared/admin/cms_menu" %>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to new_admin_promo_path, class: "button save-btn red-background", id: "csm-btn" do %>
            <span class="icon is-small">
              <%= fa_icon "plus", class: "white-text" %>
            </span>
            <span class="white-text font-is-akzidenz-ce-bold">CREATE PROMO</span>
          <% end%>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__items-table">
    <table class="table is-bordered is-fullwidth is-marginless">
      <thead>
        <tr>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Name</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Operations</th>
        </tr>
      </thead>
      <tbody id="paginationList">
        <%= render "promo_lists" %>
      </tbody>
    </table>
    <div class="tile with-25px-top-bottom-padding">
      <div class="tile is-parent is-5">
        <div class="tile is-child" id="paginator">
          <%= paginate @promos, remote: true  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/promos/index.js.erb
$("#paginationList").html("<%= escape_javascript(render("promo_lists")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@promos, remote: true)) %>");

app/views/admin/promos/new.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "coupon.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Create Promo</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>