config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  post "/graphql", to: "graphql#execute"

  devise_for :users, skip: %i[passwords registrations], controllers: {
    sessions: "admin/sessions"
  }

  authenticate :user do
    root "admin#index"
    namespace :admin do
      resources :products, only: :index do
        collection do
          get "fetch_by_type", as: "fetch_products_by_type", to: "products#fetch_by_type"
          get "featured_meals", to: "products#featured_meals"
        end
        member do
          post   "set_as_featured",   as: "set_meal_as_featured",   to: "products#featured_meal"
          delete "set_as_unfeatured", as: "set_meal_as_unfeatured", to: "products#unfeatured_meal"
        end
      end
      put "value_meals/:id/update_status", as: "update_value_meal_status", to: "value_meals#update_status"
      resources :alacartes
      resources :branches, except: :show
      resources :coupons, except: :show
      resources :delivery_numbers, only: %i[edit update]
      resources :meal_options, except: :show do
        collection do
          get "fetch_sorted_meals", to: "meal_options#fetch_sorted_meals"
        end
      end
      resources :news
      resources :orders, only: :index
      resources :promos, except: :show
      resources :static_pages, only: :index
      resources :upsells, except: :show
      resources :users, except: :show
      resources :value_meals
      resources :coupon_utilizations, only: :index
      resources :variances, except: :show
      resources :notifications, except: :show
      resources :categories, except: :show
      resources :home_contents, except: :show
      resources :user_manuals, except: :show
    end
    if %i[development? staging?].any? { |e| Rails.env.send(e) }
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    end
  end
end

app/models/value_meal.rb
# == Schema Information
#
# Table name: value_meals
#
#  active_at       :datetime
#  alacarte_id     :integer
#  availability    :string
#  category_id     :integer
#  created_at      :datetime         not null
#  discounted_rice :boolean
#  displayed_at    :datetime
#  id              :integer          not null, primary key
#  image_source    :string
#  is_breakfast    :boolean
#  legacy_sections :string
#  name            :string
#  order_id        :integer
#  schedule_id     :integer
#  sequence_id     :integer
#  updated_at      :datetime         not null
#

# Model for value meals
class ValueMeal < ApplicationRecord
  mount_uploader :image_source, ImageUploader
  DEFAULT_MENU_ENTRY_CATEGORY = "mcsaver".freeze
  acts_as_list column: :sequence_id

  belongs_to :category, optional: true
  belongs_to :alacarte, optional: true
  belongs_to :schedule, foreign_key: "schedule_id",
                        inverse_of: :value_meals
  has_many :variances, as: :variable,
                       dependent: :destroy,
                       inverse_of: :variable
  has_many :product_categories, as: :categorizeable,
                                dependent: :destroy,
                                inverse_of: :categorizeable
  has_many :categories, through: :product_categories
  has_many :coupon_products, as: :productable,
                             dependent: :destroy,
                             inverse_of: :productable
  has_many :favorite_meals, as: :meal,
                            inverse_of: :meal,
                            dependent: :destroy
  has_one :featured_meal, as: :featureable,
                          dependent: :destroy,
                          inverse_of: :featureable
  accepts_nested_attributes_for :variances,
                                reject_if: :all_blank,
                                allow_destroy: true
  accepts_nested_attributes_for :product_categories,
                                reject_if: :all_blank,
                                allow_destroy: true

  def self.search(keyword:, category:)
    fetched_category = fetch_category(category: category)
    where(category: fetched_category&.id)
      .where("name iLIKE :keyword", keyword: "%#{keyword}%")
  end

  def self.sort_by(category:)
    fetched_category = fetch_category(category: category&.to_sym)
    where(category_id: fetched_category&.id)
  end

  def self.fetch_category(category:)
    Category.send(category)
  rescue NoMethodError
    nil
  end

  def activate!
    update(active_at: Time.zone.now)
  end

  def deactivate!
    update(active_at: nil)
  end

  def bundle?
    false
  end
end

app/controllers/admin/value_meals_controller.rb
# Controller for managing ValueMeals
class Admin::ValueMealsController < AdminController
  using StringToBoolRefinement
  before_action :set_value_meal, only: %i[
    show edit update destroy
    update_status
  ]
  set_tab :menu_entries

  def index
    @default_category = ValueMeal::DEFAULT_MENU_ENTRY_CATEGORY
    meals = fetch_meal_for(
      category: params[:category],
      search: params[:search],
      default_menu: @default_category
    )
    @value_meals = meals[:data].order(created_at: :asc)
                               .page(params[:page]).per(10)
    set_tab meals[:category], :menu_entries
  end

  def show
  end

  def new
    @value_meal = ValueMeal.new
    @value_meal.variances.new
    @value_meal.variances.each do |v|
      v.options.build
    end
  end

  def create
    mod_params = value_meal_params
    mod_params[:active_at] = active?(status: params.fetch("is_active", false))
    @value_meal = ValueMeal.new(mod_params)

    if @value_meal.save
      redirect_to admin_value_meals_path, notice: "Success"
    else
      render :new
    end
  end

  def edit
  end

  def update
    return toggle_display if params[:display].present?
    mod_params = value_meal_params
    mod_params[:active_at] = active?(status: params.fetch("is_active", false))
    if @value_meal.update_attributes(mod_params)
      redirect_to admin_value_meals_path, notice: "Success"
    else
      render :edit
    end
  end

  def destroy
    @value_meal.destroy
    message = "Successfully deleted"
    redirect_to admin_value_meals_path, notice: message
  end

  def update_status
    if params[:status].to_s.to_bool
      @value_meal.activate!
    else
      @value_meal.deactivate!
    end
    render json: { message: "Success!", status: :ok }
  end

  private

  def value_meal_params
    option_attr = %i[id choice_id section_id _destroy]
    variance_attr = [:id, :menu_name, :name, :price,
                     :poscode, :image_source, :_destroy,
                     options_attributes: option_attr]
    product_categories_attr = %i[id category_id categorizeable_type _destroy]
    params.require(:value_meal).permit(
      permitted_params,
      variances_attributes: variance_attr,
      product_categories_attributes: product_categories_attr
    )
  end

  def permitted_params
    %i[
      name is_breakfast category_id schedule_id value_meal_id discounted_rice
      image_source alacarte_id availability active_at
    ]
  end

  def set_value_meal
    @value_meal = ValueMeal.find_by(id: params[:id])
  end

  def toggle_display
    value = params[:display] == "true" ? Time.zone.today : nil
    @value_meal.update(displayed_at: value)
    render json: { message: "Success." }, status: :ok
  end

  def fetch_meal_for(category:, search:, default_menu:)
    category ||= default_menu
    {}.tap do |meals|
      meals[:data] = if search
                       ValueMeal.search(keyword: search, category: category)
                     else
                       ValueMeal.sort_by(category: category)
                     end
      meals[:category] = category
    end
  end

  def active?(status:)
    status ? Time.zone.now : nil
  end
end

app/helpers/admin/value_meals_helper.rb
module Admin::ValueMealsHelper
  def value_meals
    ::ValueMeal.all
  end

  def generate_status(active:)
    active ? "Active" : "Inactive"
  end
end

app/views/admin/value_meals/_category_menu_bar.html.erb
<nav class="navbar nav-set-height is-light-gray-bg">
  <div class="container is-fluid">
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <%= tabs_tag namespace: :menu_entries, builder: MenuTabBuilder, open_tabs: { class: "navbar-start" } do |tab| %>
        <%= tab.mcsaver "Standard", admin_value_meals_path(category: "mcsaver"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.mcshare "McShare Box", admin_value_meals_path(category: "mcshare"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.happy_meal "Happy Meal", admin_value_meals_path(category: "happy_meal"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.fries_and_float "Combos", admin_value_meals_path(category: "fries_and_float"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.add_ons "Add ons", admin_value_meals_path(category: "add_ons"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
        <%= tab.extra_value_meal "Meal w/ Float", admin_value_meals_path(category: "extra_value_meal"), class: "navbar-item font-is-akzidenz-regular has-gray-text", nav_for: "meals" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/admin/value_meals/_form.html.erb
<%= form_with model: [:admin, @value_meal], local: true do |f| %>
  <%= render "shared/form_errors", object: @value_meal %>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="field">
        <div class="control">
          <%= f.text_field :name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Name" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Categories</label>
          <%= f.fields_for :product_categories do |product_category| %>
            <%= render "shared/admin/product_categories_fields", type: "ValueMeal", f: product_category %>
          <% end %>
          <div class="links">
            <%= link_to_add_association "Add Product Category", f, :product_categories, partial: "shared/admin/product_categories_fields", class: "button is-text", render_options: { locals: { type: "ValueMeal" } } %>
          </div>
        </div>
        <hr>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Alacarte</label>
          <div class="control">
            <div class="select">
              <%= f.select :alacarte_id, options_for_select(alacartes.collect{ |a| [a.name, a.id]}, @value_meal&.alacarte_id), { include_blank: 'Select Alacarte' } %>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Schedule</label>
          <div class="control">
            <div class="select">
              <%= f.select :schedule_id, options_for_select(schedules.collect{ |a| [a.title, a.id]}, @value_meal&.schedule_id), { include_blank: 'Select Schedule' } %>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Availability</label>
          <div class="control">
            <div class="select">
              <%= f.select :availability, options_for_select(available_hours.collect{ |a| [a.name, a.name]}, @value_meal&.availability), { include_blank: 'Select Availability' } %>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <input id="isActive" type="checkbox" name="is_active" class="switch is-rtl is-rounded is-success" <%= "checked" if @value_meal.active_at %> data-checkbox="switch">
        <label for="isActive">Active</label>
      </div>
      <br>
    </div>
    <div class="tile is-parent has-margin-left-30">
      <div class="field">
        <figure class="image is-4by3">
          <%= image_tag @value_meal.image_source.url, data: { container: "image" } %>
          <%= f.file_field :image_source, id: "value_meals_photo", data: { image: "layout" }, class: "is-invisible" %>
        </figure>
        <br>
        <div class="control">
          <label class="label button has-yellow-bg" for="value_meals_photo" id="uploader-label">
            <%= photo_upload_label_for(photo_is_present: @value_meal.image_source.present?) %>
          </label>
          <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 2000x2000</p>
        </div>
      </div>
    </div>
  </div>
  <div class="level is-marginless is-light-gray-bg with-20px-padding">
    <div class="level-left">
      <div class="level-item">
        <h3 class="subtitle is-4 font-is-akzidenz-bold">Variances</h3>
      </div>
    </div>
  </div>
  <br>
  <div class="field">
    <div class="control">
      <%= f.fields_for :variances do |variance| %>
        <%= render "variance_fields", f: variance %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "Add Variance", f, :variances, class: "button is-text" %>
      </div>
    </div>
    <hr>
  </div>
  <div class="field">
    <div class="control">
      <%= f.submit "SAVE", class: "save-btn white-text has-195px-width button red-background" %>
    </div>
  </div>
<% end %>

app/views/admin/value_meals/_value_meal_lists.html.erb
<% @value_meals.each do |value_meal| %>
  <tr>
    <td>
      <figure class="image is-64x64">
        <%= image_tag value_meal.image_source, alt: "" %>
      </figure>
    </td>
    <td><%= value_meal.name %></td>
    <td><%= generate_status(active: value_meal.active_at) %></td>
    <td><%= value_meal.availability %></td>
    <td>
      <div class="tile is-vertical">
        <%= link_to edit_admin_value_meal_path(value_meal), class: "edit-btn is-size-7" do %>
          <span class="icon is-small">
            <%= fa_icon "edit", class: "has-light-green-text" %>
          </span>
          EDIT
        <% end %>
        <div class="field">
          <input id='<%= "switch_#{value_meal.id}" %>' type="checkbox" name="switchRoundedSuccess" class="switch is-rounded is-success" data-link-url="<%= admin_update_value_meal_status_path(value_meal.id) %>" onchange="updateMealStatus(this)" <%= "checked" if value_meal.active_at %>>
          <label for='<%= "switch_#{value_meal.id}" %>', class='<%= value_meal.active_at ? "has-light-green-text" : "red-text" %>', id: "switch_status">
            <%= generate_status(active: value_meal.active_at) %>
          </label>
        </div>
        <div class="field">
          <input id='<%= "switch_featured_#{value_meal.id}" %>' type="checkbox"
          name="switchRoundedSuccess" class="switch is-rounded is-success"
          data-featured-url="<%= set_meal_as_featured_admin_product_path(value_meal.id, type: "ValueMeal") %>"
          data-unfeatured-url="<%= set_meal_as_unfeatured_admin_product_path(value_meal.id, type: "ValueMeal") %>"
          data-featured="meal" <%= "checked" if value_meal.featured_meal %>>
          <label for='<%= "switch_featured_#{value_meal.id}" %>',
            class='<%= value_meal.featured_meal ? "has-light-green-text" : "red-text" %>', id: "switch_featured">
            Featured
          </label>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/value_meals/_variance_fields.html.erb
<div class="nested-fields">
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="field">
        <div class="control">
          <%= f.text_field :menu_name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Menu Name" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Name" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :price, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Price" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :poscode, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "POS code" %>
        </div>
      </div>
    </div>
    <div class="tile is-parent has-margin-left-30">
      <div class="field">
        <figure class="image is-4by3">
          <%= image_tag f.object.image_source.url, data: { container: "image" } %>
          <%= f.file_field :image_source, id: "variance_photo", data: { image: "layout" }, class: "is-invisible"%>
        </figure>
        <br>
        <div class="control">
          <label class="label button has-yellow-bg" for="variance_photo" id="uploader-label">
            <%= photo_upload_label_for(photo_is_present: f.object.image_source.present?) %>
          </label>
          <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 2000x2000</p>
        </div>
      </div>
    </div>
  </div>
  <div class="level is-marginless is-light-gray-bg with-20px-padding">
    <div class="level-left">
      <div class="level-item">
        <h3 class="subtitle is-4 font-is-akzidenz-bold">With Items</h3>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Drinks</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/drinks", f: option if option.object&.meal_option&.drink? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Drinks", f, :options, partial: "admin/value_meals/options/drinks", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Fries</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/fries", f: option if option.object&.meal_option&.fries? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Fries", f, :options, partial: "admin/value_meals/options/fries", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Special Fries</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/special_fries", f: option if option.object&.meal_option&.special_fries? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Special Fries", f, :options, partial: "admin/value_meals/options/special_fries", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Best to Go With</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/best_with", f: option if option.object&.meal_option&.best_with? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Best to Go With", f, :options, partial: "admin/value_meals/options/best_with", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Sides</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/sides", f: option if option.object&.meal_option&.sides? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Sides", f, :options, partial: "admin/value_meals/options/sides", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="tile is-child">
        <h3 class="subtitle is-4 red-text font-is-akzidenz-bold">Sauces</h3>
      </div>
      <div class="tile is-child">
        <div class="field">
          <div class="control">
            <%= f.fields_for :options do |option| %>
              <%= render "admin/value_meals/options/sauces", f: option if option.object&.meal_option&.sauce? %>
            <% end %>
            <div class="links">
              <%= link_to_add_association "Add Sauce", f, :options, partial: "admin/value_meals/options/sauces", class: "buttton is-text" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to_remove_association "Remove Variance", f, class: "button is-text" %>
</div>

app/views/admin/value_meals/edit.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "fries.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Edit Food Menu Entry</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/value_meals/index.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "fries.png" %>
          </figure>
        </div>
        <div class="level-item has-margin-left-15">
          <h1 class="title is-3 is-black-text has-font-akzidenz-bold">Food Menu Entries</h1>
        </div>
        <div class="level-item">
          <%= render "category_menu_bar" %>
        </div>
      </div>
      <div class="level-right">
        <%= form_with url: admin_value_meals_path(category: params[:category] || @default_category), method: :get, remote: true do |f| %>
          <div class="field has-addons">
            <div class="control has-icons-left">
              <%= f.text_field :search, class: "input", placeholder: "Search", data: { trigger: "search" } %>
              <span class="icon is-small is-left">
                <%= fa_icon("search", class: "has-text-grey-light") %>
              </span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to new_admin_value_meal_path, class: "button save-btn red-background" do %>
      <span class="icon is-small">
        <%= fa_icon "plus", class: "white-text" %>
      </span>
      <span class="white-text font-is-akzidenz-ce-bold">ADD NEW FOOD ENTRY</span>
    <% end%>
  </div>
  <div class="wrapper__content__list__items-table">
    <table class="table is-bordered is-fullwidth is-marginless">
      <thead>
        <tr>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Photo</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Name</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Status</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">####</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Operations</th>
        </tr>
      </thead>
      <tbody id="paginationList">
        <%= render "value_meal_lists" %>
      </tbody>
    </table>
    <div class="tile with-25px-top-bottom-padding">
      <div class="tile is-parent is-5">
        <div class="tile is-child" id="paginator">
          <%= paginate @value_meals, remote: true  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/value_meals/index.js.erb
$("#paginationList").html("<%= escape_javascript(render("value_meal_lists")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@value_meals, remote: true)) %>");

app/views/admin/value_meals/new.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "fries.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Create Food Menu Entry</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/value_meals/show.html.erb
<div class="row">
  <h1 class="title is-1"><%= @value_meal.name %></h1>
</div>
<div class="row">
  <h1 class="title is-1"><%= @value_meal.alacarte&.name %></h1>
</div>
<div class="row">
  <p>Category: <%= @value_meal.category&.name %></p>
</div>
<div class="row">
  <p>Is Breakfast: <%= @value_meal.is_breakfast %></p>
</div>
<div class="row">
  <p>Schedule: <%= @value_meal.schedule.title %></p>
</div>
<div class="row">
  <figure class="image is-128x128">
    <%= image_tag @value_meal.image_source, alt: "" %>
  </figure>
</div>
<div class="row">
  <p>Order ID: <%= @value_meal.order_id %></p>
</div>
<div class="row">
  <p>Discounted Rice: <%= @value_meal.discounted_rice %></p>
</div>
<div class="row">
  <hr>
  <h3 class="title is-3">Variances</h3>
  <% @value_meal.variances.each.with_index(1) do |variance, i| %>
    <h4 class="title is-4">variance <%= i %></h4>
    <p>Menu Name: <%= variance.menu_name %></p>
    <p>Code Name: <%= variance.code_name %></p>
    <p>Name: <%= variance.name %></p>
    <p>POS Code: <%= variance.poscode %></p>
    <p>Price: <%= variance.price %></p>
    <p>Image:
      <figure class="image is-128x128">
        <%= image_tag variance.image, alt: "" unless variance.image.nil? %>
      </figure></p>
    <p>Group ID: <%= variance.group_id %></p>
    <p>Best With: <%= variance.best_with %></p>
    <div class="row">
      <h3 class="title is-3">Options</h3>
      <% variance.options.each.with_index(1) do |option, i| %>
        <h4 class="title is-4">Option <%= i %></h4>
        <p>Meal Option: <%= option.meal_option.name %></p>
        <p>Section: <%= option.section.title %></p>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

<%= link_to "Edit", edit_admin_value_meal_path %> <br>
<%= link_to "Delete", admin_value_meal_path(@value_meal), method: :delete %>