config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  post "/graphql", to: "graphql#execute"

  devise_for :users, skip: %i[passwords registrations], controllers: {
    sessions: "admin/sessions"
  }

  authenticate :user do
    root "admin#index"
    namespace :admin do
      resources :products, only: :index do
        collection do
          get "fetch_by_type", as: "fetch_products_by_type", to: "products#fetch_by_type"
          get "featured_meals", to: "products#featured_meals"
        end
        member do
          post   "set_as_featured",   as: "set_meal_as_featured",   to: "products#featured_meal"
          delete "set_as_unfeatured", as: "set_meal_as_unfeatured", to: "products#unfeatured_meal"
        end
      end
      put "value_meals/:id/update_status", as: "update_value_meal_status", to: "value_meals#update_status"
      resources :alacartes
      resources :branches, except: :show
      resources :coupons, except: :show
      resources :delivery_numbers, only: %i[edit update]
      resources :meal_options, except: :show do
        collection do
          get "fetch_sorted_meals", to: "meal_options#fetch_sorted_meals"
        end
      end
      resources :news
      resources :orders, only: :index
      resources :promos, except: :show
      resources :static_pages, only: :index
      resources :upsells, except: :show
      resources :users, except: :show
      resources :value_meals
      resources :coupon_utilizations, only: :index
      resources :variances, except: :show
      resources :notifications, except: :show
      resources :categories, except: :show
      resources :home_contents, except: :show
      resources :user_manuals, except: :show
    end
    if %i[development? staging?].any? { |e| Rails.env.send(e) }
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    end
  end
end

app/models/alacarte.rb
# == Schema Information
#
# Table name: alacartes
#
#  best_with        :integer
#  category_id      :integer
#  created_at       :datetime         not null
#  description      :text
#  discounted_rice  :boolean
#  displayed_at     :datetime
#  group_id         :integer
#  id               :integer          not null, primary key
#  image_source     :string
#  legacy_sections  :string
#  name             :string
#  product_order_id :integer
#  schedule_id      :integer
#  sequence_id      :integer
#  updated_at       :datetime         not null
#

# Model for alacarte meals
class Alacarte < ApplicationRecord
  mount_uploader :image_source, ImageUploader
  acts_as_list column: :sequence_id

  belongs_to :category, optional: true
  belongs_to :schedule, foreign_key: "schedule_id",
                        inverse_of: :alacartes
  has_many :variances, as: :variable,
                       dependent: :destroy,
                       inverse_of: :variable
  has_many :value_meals, dependent: :destroy
  has_many :product_categories, as: :categorizeable,
                                dependent: :destroy,
                                inverse_of: :categorizeable
  has_many :categories, through: :product_categories
  has_many :favorite_meals, as: :meal,
                            inverse_of: :meal,
                            dependent: :destroy
  has_many :coupon_products, as: :productable,
                             dependent: :destroy,
                             inverse_of: :productable
  has_one :product_bundle, dependent: :destroy
  has_many :upsells, dependent: :destroy
  has_one :featured_meal, as: :featureable,
                          dependent: :destroy,
                          inverse_of: :featureable
  accepts_nested_attributes_for :variances,
                                reject_if: :all_blank,
                                allow_destroy: true
  accepts_nested_attributes_for :product_categories,
                                reject_if: :all_blank,
                                allow_destroy: true

  def self.search(keyword:)
    where("name iLIKE :keyword", keyword: "%#{keyword}%")
  end

  def bundle?
    product_bundle.present?
  end
end

app/controllers/admin/alacartes_controller.rb
# Controller for managing Alacarte model
class Admin::AlacartesController < AdminController
  set_tab :alacarte
  before_action :set_alacarte, only: %i[show edit update destroy]

  def index
    @alacartes = if (search_keyword = params[:search])
                   Alacarte.search(keyword: search_keyword)
                 else
                   Alacarte.includes(:category, :variances).all
                 end
    @alacartes = Kaminari.paginate_array(@alacartes).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @alacarte = Alacarte.new
    @alacarte.variances.new
    @alacarte.variances.each do |v|
      v.options.build
    end
  end

  def create
    @alacarte = Alacarte.new(alacarte_params)
    if @alacarte.save
      redirect_to admin_alacartes_path, notice: "Success"
    else
      render :new
    end
  end

  def edit
  end

  def update
    return toggle_display if params[:display].present?
    if @alacarte.update_attributes(alacarte_params)
      redirect_to admin_alacartes_path, notice: "Success"
    else
      render :edit
    end
  end

  def destroy
    @alacarte.destroy
    message = "Successfully deleted"
    redirect_to admin_alacartes_path, notice: message
  end

  private

  def alacarte_params
    permitted_params = :name, :description, :discounted_rice,
                       :image_source, :category_id, :schedule_id
    option_attr = %i[id choice_id section_id _destroy]
    variance_attr = [:id, :menu_name, :name, :price, :poscode,
                     :image_source, :_destroy, options_attributes: option_attr]
    product_categories_attr = %i[id category_id categorizeable_type _destroy]
    params.require(:alacarte).permit(
      permitted_params,
      variances_attributes: variance_attr,
      product_categories_attributes: product_categories_attr
    )
  end

  def set_alacarte
    @alacarte = Alacarte.find_by(id: params[:id])
  end

  def toggle_display
    value = params[:display] == "true" ? Time.zone.today : nil
    @alacarte.update(displayed_at: value)
    render json: { message: "Success." }, status: :ok
  end
end

app/helpers/admin/alacarte_helper.rb
module Admin::AlacarteHelper
  def alacartes
    ::Alacarte.all
  end
end

app/views/admin/alacartes/_alacarte_lists.html.erb
<% @alacartes.each do |alacarte| %>
  <tr>
    <td>
      <figure class="image is-64x64">
        <%= image_tag alacarte.image_source, alt: "" %>
      </figure>
    </td>
    <td><%= alacarte.name %></td>
    <td><%= alacarte.description %></td>
    <td>
      <div class="tile is-vertical">
        <%= link_to edit_admin_alacarte_path(alacarte), class: "edit-btn is-size-7" do %>
          <span class="icon is-small">
            <%= fa_icon "edit", class: "has-light-green-text" %>
          </span>
          EDIT
        <% end %>
        <%= link_to admin_alacarte_path(alacarte), class: "delete-btn is-size-7", method: :delete do %>
          <span class="icon is-small">
            <%= fa_icon "trash", class: "red-text" %>
          </span>
          DELETE
        <% end %>
        <div class="field">
          <input id='<%= "switch_featured_#{alacarte.id}" %>' type="checkbox"
          name="switchRoundedSuccess" class="switch is-rounded is-success"
          data-featured-url="<%= set_meal_as_featured_admin_product_path(alacarte.id, type: "Alacarte") %>"
          data-unfeatured-url="<%= set_meal_as_unfeatured_admin_product_path(alacarte.id, type: "Alacarte") %>"
          data-featured="meal" <%= "checked" if alacarte.featured_meal %>>
          <label for='<%= "switch_featured_#{alacarte.id}" %>',
            class='<%= alacarte.featured_meal ? "has-light-green-text" : "red-text" %>', id: "switch_featured">
            Featured
          </label>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/alacartes/_form.html.erb
<%= form_with model: [:admin, @alacarte], local: true do |f| %>
  <%= render "shared/form_errors", object: @alacarte %>
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="field">
        <label class="label">Name</label>
        <div class="control">
          <%= f.text_field :name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless" %>
        </div>
      </div>
      <div class="field">
        <label class="label">Description</label>
        <div class="control">
          <%= f.text_area :description, class: "textarea" %>
        </div>
      </div>
      <div class="field">
        <label class="label">Discounted Rice</label>
        <div class="control">
          True <%= f.radio_button :discounted_rice, true %>
          False <%= f.radio_button :discounted_rice, false %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Categories</label>
          <%= f.fields_for :product_categories do |product_category| %>
            <%= render "shared/admin/product_categories_fields", type: "Alacarte", f: product_category %>
          <% end %>
          <div class="links">
            <%= link_to_add_association "Add Product Category", f, :product_categories, partial: "shared/admin/product_categories_fields", class: "button is-text", render_options: { locals: { type: "Alacarte" } } %>
          </div>
        </div>
        <hr>
      </div>
      <div class="field">
        <label class="label">Schedule</label>
        <div class="control">
          <div class="select">
            <%= f.select :schedule_id, options_for_select(schedules.collect{ |a| [a.title, a.id] }) %>
          </div>
        </div>
      </div>
    </div>
    <div class="tile is-parent has-margin-left-30">
      <div class="field">
        <figure class="image is-4by3">
          <%= image_tag @alacarte.image_source.url, data: { container: "image" } %>
          <%= f.file_field :image_source, id: "photo", data: { image: "layout" }, class: "is-invisible" %>
        </figure>
        <br>
        <div class="control">
          <label class="label button has-yellow-bg" for="photo" id="uploader-label">
            <%= photo_upload_label_for(photo_is_present: @alacarte.image_source.present?) %>
          </label>
          <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 2000x2000</p>
        </div>
      </div>
    </div>
  </div>
  <div class="level is-marginless is-light-gray-bg with-20px-padding">
    <div class="level-left">
      <div class="level-item">
        <h3 class="subtitle is-4 font-is-akzidenz-bold">Variances</h3>
      </div>
    </div>
  </div>
  <br>
  <div class="field">
    <div class="control">
      <%= f.fields_for :variances do |variance| %>
        <%= render "variance_fields", f: variance %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "Add Variance", f, :variances, class: "button is-text" %>
      </div>
    </div>
    <hr>
  </div>
  <div class="field">
    <div class="control">
      <%= f.submit "SAVE", class: "save-btn white-text has-195px-width button red-background" %>
    </div>
  </div>
<% end %>

app/views/admin/alacartes/_option_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <label class="label">Meal Option</label>
    <div class="control">
      <div class="select">
        <%= f.select :choice_id, options_for_select(meal_options.collect{ |a| [a.name, a.id] }) %>
      </div>
    </div>
  </div>
  <div class="field">
    <label class="label">Section</label>
    <div class="control">
      <div class="select">
        <%= f.select :section_id, options_for_select(sections.collect{ |a| [a.title, a.id] }) %>
      </div>
    </div>
  </div>
  <%= link_to_remove_association "Remove Meal Option", f, class: "button is-text" %>
</div>

app/views/admin/alacartes/_variance_fields.html.erb
<div class="nested-fields">
  <div class="tile">
    <div class="tile is-parent is-vertical">
      <div class="field">
        <div class="control">
          <%= f.text_field :menu_name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Menu Name" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :name, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Name" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :price, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "Price" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_field :poscode, class: "input has-no-top-side-border is-shadowless is-radiusless is-paddingless", placeholder: "POS code" %>
        </div>
      </div>
    </div>
    <div class="tile is-parent has-margin-left-30">
      <div class="field">
        <figure class="image is-4by3">
          <%= image_tag f.object.image_source.url, data: { container: "image" } %>
          <%= f.file_field :image_source, id: "variance_photo", data: { image: "layout" }, class: "is-invisible"%>
        </figure>
        <br>
        <div class="control">
          <label class="label button has-yellow-bg" for="variance_photo" id="uploader-label">
            <%= photo_upload_label_for(photo_is_present: f.object.image_source.present?) %>
          </label>
          <p class="is-size-7 has-text-grey">Please upload a square image, preferrably 2000x2000</p>
        </div>
      </div>
    </div>
  </div>
  <%= link_to_remove_association "Remove Variance", f, class: "button is-text" %>
</div>

app/views/admin/alacartes/edit.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "burger.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Edit Alacarte</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/alacartes/index.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "burger.png" %>
          </figure>
        </div>
        <div class="level-item has-margin-left-15">
          <h1 class="title is-3 is-black-text has-font-akzidenz-bold">Alacarte</h1>
        </div>
      </div>
      <div class="level-right">
        <%= form_with url: admin_alacartes_path, method: :get, remote: true do |f| %>
          <div class="field has-addons">
            <div class="control has-icons-left">
              <%= f.text_field :search, class: "input", placeholder: "Search", data: { trigger: "search" } %>
              <span class="icon is-small is-left">
                <%= fa_icon("search", class: "has-text-grey-light") %>
              </span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to new_admin_alacarte_path, class: "button save-btn red-background" do %>
      <span class="icon is-small">
        <%= fa_icon "plus", class: "white-text" %>
      </span>
      <span class="white-text font-is-akzidenz-ce-bold">ADD NEW ALACARTE</span>
    <% end%>
  </div>
  <div class="wrapper__content__list__items-table">
    <table class="table is-bordered is-fullwidth is-marginless">
      <thead>
        <tr>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Image</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Name</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Description</th>
          <th class="is-borderless is-size-6 font-is-akzidenz-regular with-20px-top-bottom-padding">Operations</th>
        </tr>
      </thead>
      <tbody id="paginationList">
        <%= render "alacarte_lists" %>
      </tbody>
    </table>
    <div class="tile with-25px-top-bottom-padding">
      <div class="tile is-parent is-5">
        <div class="tile is-child" id="paginator">
          <%= paginate @alacartes, remote: true  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/alacartes/index.js.erb
$("#paginationList").html("<%= escape_javascript(render("alacarte_lists")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@alacartes, remote: true)) %>");

app/views/admin/alacartes/new.html.erb
<div class="tile is-vertical wrapper__content__list is-white-bg">
  <div class="wrapper__content__list__header">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <figure class="image is-32x32">
            <%= image_tag "burger.png" %>
          </figure>
        </div>
        <div class="level-item">
          <h1 class="title is-3 has-margin-left-30">Create Alacarte</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper__content__list__form">
    <%= render "form" %>
  </div>
</div>

app/views/admin/alacartes/show.html.erb
<div class="row">
  <h1 class="title is-1"><%= @alacarte.name %></h1>
</div>
<div class="row">
  <p>Category: <%= @alacarte.category&.name %></p>
</div>
<div class="row">
  <p>Description: <%= @alacarte.description %></p>
</div>
<div class="row">
  <p>Schedule: <%= @alacarte.schedule.title %></p>
</div>
<div class="row">
  <figure class="image is-128x128">
    <%= image_tag @alacarte.image_source, alt: "" %>
  </figure>
</div>
<div class="row">
  <p>Group ID: <%= @alacarte.group_id %></p>
</div>
<div class="row">
  <p>Product Order ID: <%= @alacarte.product_order_id %></p>
</div>
<div class="row">
  <p>Discounted Rice: <%= @alacarte.discounted_rice %></p>
</div>
<div class="row">
  <hr>
  <h3 class="title is-3">Variances</h3>
  <% @alacarte.variances.each.with_index(1) do |variance, i| %>
    <h4 class="title is-4">variance <%= i %></h4>
    <p>Menu Name: <%= variance.menu_name %></p>
    <p>Code Name: <%= variance.code_name %></p>
    <p>Name: <%= variance.name %></p>
    <p>POS Code: <%= variance.poscode %></p>
    <p>Price: <%= variance.price %></p>
    <p>Image:
      <figure class="image is-128x128">
        <%= image_tag variance.image_source.url, alt: "" %>
      </figure></p>
    <p>Group ID: <%= variance.group_id %></p>
    <p>Best With: <%= variance.best_with %></p>
    <div class="row">
      <h3 class="title is-3">Options</h3>
      <% variance.options.each.with_index(1) do |option, i| %>
        <h4 class="title is-4">Option <%= i %></h4>
        <p>Meal Option: <%= option.meal_option.name %></p>
        <p>Section: <%= option.section.title %></p>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

<%= link_to "Edit", edit_admin_alacarte_path %> <br>
<%= link_to "Delete", admin_alacarte_path(@alacarte), method: :delete %>